name: june_view
description: "view framework by june, divide view,action,event and state for easy to use."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_view

version: 1.7.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  june:  #@add
  styled_widget:  #@add
  after_layout:  #@add
  device_preview:
  flutter_screenutil:
  gap: #@add
  flutter_svg:  #@add

dev_dependencies:
  device_preview_module: #@add
  flutter_lints:
  flutter_lints_module: #@add
  flutter_test:
    sdk: flutter

  screenutil_module:  #@add

flutter:
  uses-material-design: true