name: june_view
description: "JuneFlow Module"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_view

version: 1.4.4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util: ^0.8.19
  june: ^0.8.8 #@add
  styled_widget: ^0.4.0+3 #@add
  after_layout: ^1.2.0 #@add
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gap: ^3.0.1 #@add
  flutter_svg: ^2.0.10+1 #@add

dev_dependencies:
  device_preview_module: ^0.1.0 #@add
  flutter_lints: ^3.0.2
  flutter_lints_module: ^0.0.1+7 #@add
  flutter_test:
    sdk: flutter

  hive_module: ^1.0.0+3 #@add
  screenutil_module: ^1.0.0+1 #@add

flutter:
  uses-material-design: true