name: june_view
description: "view framework by june, divide view,action,event and state for easy to use."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_view

version: 1.7.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util: ^0.8.19
  june: ^0.8.8 #@add
  styled_widget: ^0.4.0+3 #@add
  after_layout: ^1.2.0 #@add
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1 #@add
  flutter_svg: ^2.0.10+1 #@add

dev_dependencies:
  device_preview_module: #@add
  flutter_lints:
  flutter_lints_module: #@add
  flutter_test:
    sdk: flutter

  screenutil_module:  #@add

flutter:
  uses-material-design: true